Repository tact-lang/tact-docs, pull requests merged in 2024-03, with the labels that each got.

#118 feat/fix: Large Book Update
  pages/book/_meta.js
  pages/book/composite-types.mdx
  pages/book/cookbook.mdx
  pages/book/exit-codes.mdx
  pages/book/func.mdx
  pages/book/index.mdx
  pages/book/integers.mdx
  pages/book/operators.mdx
  pages/book/statements.mdx
  pages/book/types.mdx
  pages/index.mdx
  pages/language/ref/_meta.js
  pages/language/ref/exit-codes.mdx
Labels: scope: Large

#119 fix: use `+=`, `*=`, `-=` operators
  .github/temp-archive/learn/wallet/wallet-2.mdx
  pages/book/cookbook.mdx
  pages/book/exit-codes.mdx
  pages/book/functions.mdx
  pages/book/types.mdx
  pages/language/libs/dns.mdx
Labels: tact update

#140 feat: Privilege check in the Cookbook
  pages/book/cookbook.mdx
  pages/book/receive.mdx
Labels: has dependency
